[Service]
  Port = "8000"
  Environment = "development"
  RepoURL = "https://git.xenonstack.com/api/v4/projects/885/repository/archive.zip?sha=develop"
  RepoPrivateKey = "xxxx"

[Database]
  name = "csecurity"
  host = "localhost"
  port = "5432"
  user = "postgres"
  pass = "root"
  ideal = "10"


[NatsServer]
  url = "nats://172.16.200.201:32256"
  token = "xxxx"
  username = "user"
  password = "xxxx"

[Hubspot]
	WebsiteID=""
	PortalID=""
